# Generated by Django 5.2.13 on 2026-04-13 17:29

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(db_column='departmentId', primary_key=True, serialize=False)),
                ('departName', models.CharField(db_column='departName', max_length=100, unique=True)),
                ('specialization', models.CharField(blank=True, db_column='specialization', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='HealthCard',
            fields=[
                ('cardId', models.AutoField(db_column='cardId', primary_key=True, serialize=False)),
                ('cardName', models.CharField(db_column='cardName', max_length=100, unique=True)),
                ('awesomeDesc', models.TextField(db_column='awesomeDesc')),
                ('crappyDesc', models.TextField(db_column='crappyDesc')),
            ],
            options={
                'db_table': 'HealthCard',
            },
        ),
        migrations.CreateModel(
            name='HealthSession',
            fields=[
                ('sessionId', models.AutoField(db_column='sessionId', primary_key=True, serialize=False)),
                ('sessionName', models.CharField(db_column='sessionName', max_length=100)),
                ('sessionDate', models.DateField(db_column='sessionDate')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'HealthSession',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skillId', models.AutoField(db_column='skillId', primary_key=True, serialize=False)),
                ('skillName', models.CharField(db_column='skillName', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('typeId', models.AutoField(db_column='typeId', primary_key=True, serialize=False)),
                ('typeName', models.CharField(db_column='typeName', max_length=50)),
            ],
            options={
                'db_table': 'TeamType',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userId', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=50, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('email', models.EmailField(db_column='email', max_length=100, unique=True)),
                ('first_name', models.CharField(db_column='fName', max_length=50)),
                ('last_name', models.CharField(db_column='lName', max_length=50)),
                ('dob', models.DateField(blank=True, db_column='dob', null=True)),
                ('about_me', models.TextField(blank=True, db_column='aboutMe', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empId', models.AutoField(db_column='empId', primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, db_column='position', max_length=50, null=True)),
                ('user', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.AutoField(db_column='messageId', primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, db_column='subject', max_length=200, null=True)),
                ('body', models.TextField(blank=True, db_column='body', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('sentAt', models.DateTimeField(blank=True, db_column='sentAt', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('fail', 'Fail')], db_column='status', max_length=20)),
                ('senderMsgDeleted', models.BooleanField(db_column='senderMsgDeleted', default=False)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Message',
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRead', models.BooleanField(db_column='isRead', default=False)),
                ('recipMsgDeleted', models.BooleanField(db_column='recipMsgDeleted', default=False)),
                ('message', models.ForeignKey(db_column='messageId', on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='portal.message')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Message_Recipient',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notifId', models.AutoField(db_column='notifId', primary_key=True, serialize=False)),
                ('entityId', models.IntegerField(blank=True, db_column='entityId', null=True)),
                ('entityType', models.CharField(blank=True, choices=[('Meeting', 'Meeting'), ('MeetingInvitation', 'MeetingInvitation'), ('Message', 'Message'), ('Team', 'Team'), ('HealthSession', 'HealthSession')], db_column='entityType', max_length=50, null=True)),
                ('message', models.TextField(db_column='message')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'Notification',
                'constraints': [models.CheckConstraint(condition=models.Q(('entityType__in', ['Meeting', 'MeetingInvitation', 'Message', 'Team', 'HealthSession']), ('entityType__isnull', True), _connector='OR'), name='notification_entity_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRead', models.BooleanField(db_column='isRead', default=False)),
                ('notif', models.ForeignKey(db_column='notifId', on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='portal.notification')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notification_Recipient',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(db_column='teamId', primary_key=True, serialize=False)),
                ('teamName', models.CharField(db_column='teamName', max_length=100)),
                ('descrip', models.TextField(blank=True, db_column='descrip', null=True)),
                ('responsib', models.TextField(blank=True, db_column='responsib', null=True)),
                ('focusArea', models.CharField(blank=True, db_column='focusArea', max_length=100, null=True)),
                ('standupTime', models.TimeField(blank=True, db_column='standupTime', null=True)),
                ('standupLink', models.CharField(blank=True, db_column='standupLink', max_length=255, null=True)),
                ('concurrentProjs', models.IntegerField(blank=True, db_column='concurrentProjs', null=True)),
                ('workstreamMf', models.CharField(blank=True, db_column='workstreamMf', max_length=100, null=True)),
                ('jiraProjName', models.CharField(blank=True, db_column='jiraProjName', max_length=100, null=True)),
                ('jiraBoardLink', models.CharField(blank=True, db_column='jiraBoardLink', max_length=255, null=True)),
                ('commChann', models.CharField(blank=True, db_column='commChann', max_length=100, null=True)),
                ('teamWiki', models.CharField(blank=True, db_column='teamWiki', max_length=255, null=True)),
                ('agilePractice', models.CharField(blank=True, db_column='agilePractice', max_length=50, null=True)),
                ('teamStatus', models.CharField(db_column='teamStatus', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('disbandedAt', models.DateTimeField(blank=True, db_column='disbandedAt', null=True)),
                ('department', models.ForeignKey(db_column='departmentId', on_delete=django.db.models.deletion.PROTECT, to='portal.department')),
                ('type', models.ForeignKey(blank=True, db_column='typeId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.teamtype')),
            ],
            options={
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('repoId', models.AutoField(db_column='repoId', primary_key=True, serialize=False)),
                ('repoName', models.CharField(db_column='repoName', max_length=100)),
                ('repoUrl', models.CharField(blank=True, db_column='repoUrl', max_length=255, null=True)),
                ('isMainProj', models.BooleanField(db_column='isMainProj', default=False)),
                ('team', models.ForeignKey(db_column='teamId', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portal.team')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='HealthVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], db_column='rating', max_length=10)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('stable', 'Stable'), ('down', 'Down')], db_column='trend', max_length=10)),
                ('votedAt', models.DateTimeField(auto_now_add=True, db_column='votedAt')),
                ('card', models.ForeignKey(db_column='cardId', on_delete=django.db.models.deletion.CASCADE, to='portal.healthcard')),
                ('emp', models.ForeignKey(db_column='empId', on_delete=django.db.models.deletion.CASCADE, to='portal.employee')),
                ('session', models.ForeignKey(db_column='sessionId', on_delete=django.db.models.deletion.CASCADE, to='portal.healthsession')),
                ('teamId', models.ForeignKey(db_column='teamId', on_delete=django.db.models.deletion.CASCADE, to='portal.team')),
            ],
            options={
                'db_table': 'HealthVote',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='teamId',
            field=models.ForeignKey(blank=True, db_column='teamId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='portal.team'),
        ),
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencyType', models.CharField(blank=True, db_column='dependencyType', max_length=50, null=True)),
                ('downstream', models.ForeignKey(db_column='downstr_teamId', on_delete=django.db.models.deletion.CASCADE, related_name='upstream_links', to='portal.team')),
                ('upstream', models.ForeignKey(db_column='upstr_teamId', on_delete=django.db.models.deletion.CASCADE, related_name='downstream_links', to='portal.team')),
            ],
            options={
                'db_table': 'Team_Dependency',
            },
        ),
        migrations.CreateModel(
            name='TeamSkillAlloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(db_column='skillId', on_delete=django.db.models.deletion.CASCADE, to='portal.skill')),
                ('team', models.ForeignKey(db_column='teamId', on_delete=django.db.models.deletion.CASCADE, to='portal.team')),
            ],
            options={
                'db_table': 'Team_Skill_Alloc',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('actionId', models.AutoField(db_column='actionId', primary_key=True, serialize=False)),
                ('actionDescr', models.TextField(blank=True, db_column='actionDescr', null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], db_column='action', max_length=20)),
                ('entityId', models.IntegerField(blank=True, db_column='entityId', null=True)),
                ('entityType', models.CharField(blank=True, choices=[('Users', 'Users'), ('Team', 'Team'), ('Employee', 'Employee'), ('Department', 'Department'), ('Project', 'Project'), ('Meeting', 'Meeting'), ('Message', 'Message'), ('MeetingInvitation', 'MeetingInvitation'), ('TeamManager', 'TeamManager'), ('DepartmentLeader', 'DepartmentLeader'), ('Team_Skill_Alloc', 'Team_Skill_Alloc'), ('Team_Dependency', 'Team_Dependency'), ('HealthCard', 'HealthCard'), ('HealthSession', 'HealthSession'), ('HealthVote', 'HealthVote'), ('Notification', 'Notification'), ('Notification_Recipient', 'Notification_Recipient')], db_column='entityType', max_length=50, null=True)),
                ('fieldChanged', models.CharField(blank=True, db_column='fieldChanged', max_length=50, null=True)),
                ('oldValue', models.TextField(blank=True, db_column='oldValue', null=True)),
                ('newValue', models.TextField(blank=True, db_column='newValue', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Action',
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['create', 'update', 'delete'])), name='action_action_valid'), models.CheckConstraint(condition=models.Q(('entityType__in', ['Users', 'Team', 'Employee', 'Department', 'Project', 'Meeting', 'Message', 'MeetingInvitation', 'TeamManager', 'DepartmentLeader', 'Team_Skill_Alloc', 'Team_Dependency', 'HealthCard', 'HealthSession', 'HealthVote', 'Notification', 'Notification_Recipient']), ('entityType__isnull', True), _connector='OR'), name='action_entity_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentLeader',
            fields=[
                ('emp', models.OneToOneField(db_column='empId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leader_role', serialize=False, to='portal.employee')),
                ('department', models.OneToOneField(db_column='departmentId', on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='portal.department')),
            ],
            options={
                'db_table': 'DepartmentLeader',
            },
        ),
        migrations.CreateModel(
            name='TeamManager',
            fields=[
                ('emp', models.OneToOneField(db_column='empId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manager_role', serialize=False, to='portal.employee')),
                ('teamId', models.ForeignKey(db_column='teamId', on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='portal.team')),
            ],
            options={
                'db_table': 'TeamManager',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meetId', models.AutoField(db_column='meetId', primary_key=True, serialize=False)),
                ('meetingType', models.CharField(choices=[('personal', 'Personal'), ('team', 'Team'), ('standup', 'Standup')], db_column='meetingType', max_length=20)),
                ('startedAt', models.DateTimeField(db_column='startedAt')),
                ('endedAt', models.DateTimeField(blank=True, db_column='endedAt', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_column='status', default='scheduled', max_length=20)),
                ('platform', models.CharField(blank=True, db_column='platform', max_length=50, null=True)),
                ('message', models.TextField(blank=True, db_column='message', null=True)),
                ('emp', models.ForeignKey(blank=True, db_column='empId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_meetings', to='portal.employee')),
                ('teamId', models.ForeignKey(blank=True, db_column='teamId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='portal.team')),
                ('teamEmp', models.ForeignKey(blank=True, db_column='teamEmpId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_meetings', to='portal.teammanager')),
            ],
            options={
                'db_table': 'Meeting',
            },
        ),
        migrations.CreateModel(
            name='MeetingInvitation',
            fields=[
                ('invitationId', models.AutoField(db_column='invitationId', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_column='status', default='pending', max_length=20)),
                ('meet', models.ForeignKey(db_column='meetId', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='portal.meeting')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MeetingInvitation',
                'constraints': [models.UniqueConstraint(fields=('user', 'meet'), name='meeting_invitation_unique'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'declined'])), name='meeting_invitation_status_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'sent', 'fail'])), name='message_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='messagerecipient',
            constraint=models.UniqueConstraint(fields=('user', 'message'), name='message_recipient_unique'),
        ),
        migrations.AddConstraint(
            model_name='notificationrecipient',
            constraint=models.UniqueConstraint(fields=('user', 'notif'), name='notification_recipient_unique'),
        ),
        migrations.AddConstraint(
            model_name='healthvote',
            constraint=models.UniqueConstraint(fields=('emp', 'session', 'card'), name='health_vote_unique'),
        ),
        migrations.AddConstraint(
            model_name='healthvote',
            constraint=models.CheckConstraint(condition=models.Q(('rating__in', ['green', 'amber', 'red'])), name='health_vote_rating_valid'),
        ),
        migrations.AddConstraint(
            model_name='healthvote',
            constraint=models.CheckConstraint(condition=models.Q(('trend__in', ['up', 'stable', 'down'])), name='health_vote_trend_valid'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('empId', 'teamId'), name='employee_unique_emp_team'),
        ),
        migrations.AddConstraint(
            model_name='teamdependency',
            constraint=models.UniqueConstraint(fields=('upstream', 'downstream'), name='team_dep_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='teamdependency',
            constraint=models.CheckConstraint(condition=models.Q(('upstream', models.F('downstream')), _negated=True), name='team_dep_no_self_loop'),
        ),
        migrations.AddConstraint(
            model_name='teamskillalloc',
            constraint=models.UniqueConstraint(fields=('skill', 'team'), name='team_skill_unique'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('department', 'teamName'), name='team_unique_dept_name'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['scheduled', 'in_progress', 'completed', 'cancelled'])), name='meeting_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(('endedAt__isnull', True), ('endedAt__gt', models.F('startedAt')), _connector='OR'), name='meeting_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(('meetingType__in', ['personal', 'team', 'standup'])), name='meeting_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('meetingType', 'personal'), ('emp__isnull', False), ('teamEmp__isnull', True)), models.Q(('meetingType__in', ['team', 'standup']), ('teamEmp__isnull', False), ('emp__isnull', True)), _connector='OR'), name='meeting_type_host_xor'),
        ),
    ]
