# Generated by Django 5.1 on 2026-04-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamStatus',
            field=models.CharField(choices=[('active', 'Active'), ('restructuring', 'Restructuring'), ('disbanded', 'Disbanded')], db_column='teamStatus', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(('teamStatus__in', ['active', 'restructuring', 'disbanded'])), name='team_status_valid'),
        ),
    ]
