# Generated by Django 5.2.13 on 2026-04-27 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_team_teamstatus_team_team_status_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(db_column='file', upload_to='message_attachments/')),
                ('uploadedAt', models.DateTimeField(auto_now_add=True, db_column='uploadedAt')),
                ('message', models.ForeignKey(db_column='messageId', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portal.message')),
            ],
            options={
                'db_table': 'Message_Attachment',
            },
        ),
    ]
