# Generated by Django 5.1 on 2026-04-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_messageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, db_column='avatar', null=True, upload_to='avatars/'),
        ),
    ]
