# Generated by Django 5.1 on 2026-04-28 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='createdAt',
            field=models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='departmentleader',
            name='assignedAt',
            field=models.DateTimeField(db_column='assignedAt', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='joinedAt',
            field=models.DateTimeField(db_column='joinedAt', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teammanager',
            name='assignedAt',
            field=models.DateTimeField(db_column='assignedAt', default=django.utils.timezone.now),
        ),
    ]
